const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "18062212660"
const SESSION_ID = "PRABATH-MD~nXRGWJhI#7LwiF2o-8RRcU5CfgV51Hlv8kT4IbZwuUQCNsG8a-WU"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
